/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class _Camera {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public _Camera(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(_Camera obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete__Camera(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPort(GPPort value) {
    gphoto2JNI._Camera_port_set(swigCPtr, this, GPPort.getCPtr(value), value);
  }

  public GPPort getPort() {
    long cPtr = gphoto2JNI._Camera_port_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GPPort(cPtr, false);
  }

  public void setFs(SWIGTYPE_p__CameraFilesystem value) {
    gphoto2JNI._Camera_fs_set(swigCPtr, this, SWIGTYPE_p__CameraFilesystem.getCPtr(value));
  }

  public SWIGTYPE_p__CameraFilesystem getFs() {
    long cPtr = gphoto2JNI._Camera_fs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__CameraFilesystem(cPtr, false);
  }

  public void setFunctions(CameraFunctions value) {
    gphoto2JNI._Camera_functions_set(swigCPtr, this, CameraFunctions.getCPtr(value), value);
  }

  public CameraFunctions getFunctions() {
    long cPtr = gphoto2JNI._Camera_functions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CameraFunctions(cPtr, false);
  }

  public void setPl(SWIGTYPE_p__CameraPrivateLibrary value) {
    gphoto2JNI._Camera_pl_set(swigCPtr, this, SWIGTYPE_p__CameraPrivateLibrary.getCPtr(value));
  }

  public SWIGTYPE_p__CameraPrivateLibrary getPl() {
    long cPtr = gphoto2JNI._Camera_pl_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__CameraPrivateLibrary(cPtr, false);
  }

  public void setPc(SWIGTYPE_p__CameraPrivateCore value) {
    gphoto2JNI._Camera_pc_set(swigCPtr, this, SWIGTYPE_p__CameraPrivateCore.getCPtr(value));
  }

  public SWIGTYPE_p__CameraPrivateCore getPc() {
    long cPtr = gphoto2JNI._Camera_pc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__CameraPrivateCore(cPtr, false);
  }

  public _Camera() {
    this(gphoto2JNI.new__Camera(), true);
  }

}
