/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class _CameraFilesystemFuncs {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public _CameraFilesystemFuncs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(_CameraFilesystemFuncs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete__CameraFilesystemFuncs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFile_list_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_file_list_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int getFile_list_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_file_list_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setFolder_list_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_folder_list_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int getFolder_list_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_folder_list_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraList_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setPut_file_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraFile_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_put_file_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraFile_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraFile_p_void_p_struct__GPContext__int getPut_file_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_put_file_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_struct__CameraFile_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setDelete_all_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_delete_all_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_void_p_struct__GPContext__int getDelete_all_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_delete_all_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setGet_info_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_struct__CameraFileInfo_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_get_info_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_struct__CameraFileInfo_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_struct__CameraFileInfo_p_void_p_struct__GPContext__int getGet_info_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_get_info_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_struct__CameraFileInfo_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setSet_info_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_struct__CameraFileInfo_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_set_info_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_struct__CameraFileInfo_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_struct__CameraFileInfo_p_void_p_struct__GPContext__int getSet_info_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_set_info_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_struct__CameraFileInfo_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setMake_dir_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_make_dir_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int getMake_dir_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_make_dir_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setRemove_dir_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_remove_dir_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int getRemove_dir_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_remove_dir_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setGet_file_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_enum_CameraFileType_p_struct__CameraFile_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_get_file_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_enum_CameraFileType_p_struct__CameraFile_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_enum_CameraFileType_p_struct__CameraFile_p_void_p_struct__GPContext__int getGet_file_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_get_file_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_enum_CameraFileType_p_struct__CameraFile_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setDel_file_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_del_file_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int getDel_file_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_del_file_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_q_const__char_p_q_const__char_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setStorage_info_func(SWIGTYPE_p_f_p_struct__CameraFilesystem_p_p_struct__CameraStorageInformation_p_int_p_void_p_struct__GPContext__int value) {
    gphoto2JNI._CameraFilesystemFuncs_storage_info_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__CameraFilesystem_p_p_struct__CameraStorageInformation_p_int_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__CameraFilesystem_p_p_struct__CameraStorageInformation_p_int_p_void_p_struct__GPContext__int getStorage_info_func() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_storage_info_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__CameraFilesystem_p_p_struct__CameraStorageInformation_p_int_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setUnused(SWIGTYPE_p_p_void value) {
    gphoto2JNI._CameraFilesystemFuncs_unused_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getUnused() {
    long cPtr = gphoto2JNI._CameraFilesystemFuncs_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public _CameraFilesystemFuncs() {
    this(gphoto2JNI.new__CameraFilesystemFuncs(), true);
  }

}
