/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class _CameraAbilitiesList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public _CameraAbilitiesList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(_CameraAbilitiesList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete__CameraAbilitiesList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    gphoto2JNI._CameraAbilitiesList_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return gphoto2JNI._CameraAbilitiesList_count_get(swigCPtr, this);
  }

  public void setAbilities(CameraAbilities value) {
    gphoto2JNI._CameraAbilitiesList_abilities_set(swigCPtr, this, CameraAbilities.getCPtr(value), value);
  }

  public CameraAbilities getAbilities() {
    long cPtr = gphoto2JNI._CameraAbilitiesList_abilities_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CameraAbilities(cPtr, false);
  }

  public _CameraAbilitiesList() {
    this(gphoto2JNI.new__CameraAbilitiesList(), true);
  }

}
