/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class _GPPortInfoList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public _GPPortInfoList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(_GPPortInfoList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete__GPPortInfoList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInfo(GPPortInfo value) {
    gphoto2JNI._GPPortInfoList_info_set(swigCPtr, this, GPPortInfo.getCPtr(value), value);
  }

  public GPPortInfo getInfo() {
    long cPtr = gphoto2JNI._GPPortInfoList_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GPPortInfo(cPtr, false);
  }

  public void setCount(long value) {
    gphoto2JNI._GPPortInfoList_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return gphoto2JNI._GPPortInfoList_count_get(swigCPtr, this);
  }

  public _GPPortInfoList() {
    this(gphoto2JNI.new__GPPortInfoList(), true);
  }

}
