/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraFilePermissions {
  public final static CameraFilePermissions GP_FILE_PERM_NONE = new CameraFilePermissions("GP_FILE_PERM_NONE", 0);
  public final static CameraFilePermissions GP_FILE_PERM_READ = new CameraFilePermissions("GP_FILE_PERM_READ", 1 << 0);
  public final static CameraFilePermissions GP_FILE_PERM_DELETE = new CameraFilePermissions("GP_FILE_PERM_DELETE", 1 << 1);
  public final static CameraFilePermissions GP_FILE_PERM_ALL = new CameraFilePermissions("GP_FILE_PERM_ALL", 0xFF);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraFilePermissions swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraFilePermissions.class + " with value " + swigValue);
  }

  private CameraFilePermissions(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraFilePermissions(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraFilePermissions(String swigName, CameraFilePermissions swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraFilePermissions[] swigValues = { GP_FILE_PERM_NONE, GP_FILE_PERM_READ, GP_FILE_PERM_DELETE, GP_FILE_PERM_ALL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

