/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class CameraFilePath {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CameraFilePath(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CameraFilePath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_CameraFilePath(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    gphoto2JNI.CameraFilePath_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return gphoto2JNI.CameraFilePath_name_get(swigCPtr, this);
  }

  public void setFolder(String value) {
    gphoto2JNI.CameraFilePath_folder_set(swigCPtr, this, value);
  }

  public String getFolder() {
    return gphoto2JNI.CameraFilePath_folder_get(swigCPtr, this);
  }

  public CameraFilePath() {
    this(gphoto2JNI.new_CameraFilePath(), true);
  }

}
