/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraOperation {
  public final static CameraOperation GP_OPERATION_NONE = new CameraOperation("GP_OPERATION_NONE", 0);
  public final static CameraOperation GP_OPERATION_CAPTURE_IMAGE = new CameraOperation("GP_OPERATION_CAPTURE_IMAGE", 1 << 0);
  public final static CameraOperation GP_OPERATION_CAPTURE_VIDEO = new CameraOperation("GP_OPERATION_CAPTURE_VIDEO", 1 << 1);
  public final static CameraOperation GP_OPERATION_CAPTURE_AUDIO = new CameraOperation("GP_OPERATION_CAPTURE_AUDIO", 1 << 2);
  public final static CameraOperation GP_OPERATION_CAPTURE_PREVIEW = new CameraOperation("GP_OPERATION_CAPTURE_PREVIEW", 1 << 3);
  public final static CameraOperation GP_OPERATION_CONFIG = new CameraOperation("GP_OPERATION_CONFIG", 1 << 4);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraOperation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraOperation.class + " with value " + swigValue);
  }

  private CameraOperation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraOperation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraOperation(String swigName, CameraOperation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraOperation[] swigValues = { GP_OPERATION_NONE, GP_OPERATION_CAPTURE_IMAGE, GP_OPERATION_CAPTURE_VIDEO, GP_OPERATION_CAPTURE_AUDIO, GP_OPERATION_CAPTURE_PREVIEW, GP_OPERATION_CONFIG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

