/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class CameraText {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CameraText(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CameraText obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_CameraText(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setText(String value) {
    gphoto2JNI.CameraText_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return gphoto2JNI.CameraText_text_get(swigCPtr, this);
  }

  public CameraText() {
    this(gphoto2JNI.new_CameraText(), true);
  }

}
