/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraEventType {
  public final static CameraEventType GP_EVENT_UNKNOWN = new CameraEventType("GP_EVENT_UNKNOWN");
  public final static CameraEventType GP_EVENT_TIMEOUT = new CameraEventType("GP_EVENT_TIMEOUT");
  public final static CameraEventType GP_EVENT_FILE_ADDED = new CameraEventType("GP_EVENT_FILE_ADDED");
  public final static CameraEventType GP_EVENT_FOLDER_ADDED = new CameraEventType("GP_EVENT_FOLDER_ADDED");
  public final static CameraEventType GP_EVENT_CAPTURE_COMPLETE = new CameraEventType("GP_EVENT_CAPTURE_COMPLETE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraEventType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraEventType.class + " with value " + swigValue);
  }

  private CameraEventType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraEventType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraEventType(String swigName, CameraEventType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraEventType[] swigValues = { GP_EVENT_UNKNOWN, GP_EVENT_TIMEOUT, GP_EVENT_FILE_ADDED, GP_EVENT_FOLDER_ADDED, GP_EVENT_CAPTURE_COMPLETE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

