/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraFileAccessType {
  public final static CameraFileAccessType GP_FILE_ACCESSTYPE_MEMORY = new CameraFileAccessType("GP_FILE_ACCESSTYPE_MEMORY");
  public final static CameraFileAccessType GP_FILE_ACCESSTYPE_FD = new CameraFileAccessType("GP_FILE_ACCESSTYPE_FD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraFileAccessType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraFileAccessType.class + " with value " + swigValue);
  }

  private CameraFileAccessType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraFileAccessType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraFileAccessType(String swigName, CameraFileAccessType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraFileAccessType[] swigValues = { GP_FILE_ACCESSTYPE_MEMORY, GP_FILE_ACCESSTYPE_FD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

