/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraFileInfoFields {
  public final static CameraFileInfoFields GP_FILE_INFO_NONE = new CameraFileInfoFields("GP_FILE_INFO_NONE", 0);
  public final static CameraFileInfoFields GP_FILE_INFO_TYPE = new CameraFileInfoFields("GP_FILE_INFO_TYPE", 1 << 0);
  public final static CameraFileInfoFields GP_FILE_INFO_NAME = new CameraFileInfoFields("GP_FILE_INFO_NAME", 1 << 1);
  public final static CameraFileInfoFields GP_FILE_INFO_SIZE = new CameraFileInfoFields("GP_FILE_INFO_SIZE", 1 << 2);
  public final static CameraFileInfoFields GP_FILE_INFO_WIDTH = new CameraFileInfoFields("GP_FILE_INFO_WIDTH", 1 << 3);
  public final static CameraFileInfoFields GP_FILE_INFO_HEIGHT = new CameraFileInfoFields("GP_FILE_INFO_HEIGHT", 1 << 4);
  public final static CameraFileInfoFields GP_FILE_INFO_PERMISSIONS = new CameraFileInfoFields("GP_FILE_INFO_PERMISSIONS", 1 << 5);
  public final static CameraFileInfoFields GP_FILE_INFO_STATUS = new CameraFileInfoFields("GP_FILE_INFO_STATUS", 1 << 6);
  public final static CameraFileInfoFields GP_FILE_INFO_MTIME = new CameraFileInfoFields("GP_FILE_INFO_MTIME", 1 << 7);
  public final static CameraFileInfoFields GP_FILE_INFO_ALL = new CameraFileInfoFields("GP_FILE_INFO_ALL", 0xFF);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraFileInfoFields swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraFileInfoFields.class + " with value " + swigValue);
  }

  private CameraFileInfoFields(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraFileInfoFields(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraFileInfoFields(String swigName, CameraFileInfoFields swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraFileInfoFields[] swigValues = { GP_FILE_INFO_NONE, GP_FILE_INFO_TYPE, GP_FILE_INFO_NAME, GP_FILE_INFO_SIZE, GP_FILE_INFO_WIDTH, GP_FILE_INFO_HEIGHT, GP_FILE_INFO_PERMISSIONS, GP_FILE_INFO_STATUS, GP_FILE_INFO_MTIME, GP_FILE_INFO_ALL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

