/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class CameraFunctions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CameraFunctions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CameraFunctions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_CameraFunctions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPre_func(SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_pre_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int getPre_func() {
    long cPtr = gphoto2JNI.CameraFunctions_pre_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int(cPtr, false);
  }

  public void setPost_func(SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_post_func_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int getPost_func() {
    long cPtr = gphoto2JNI.CameraFunctions_post_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int(cPtr, false);
  }

  public void setExit(SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_exit_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int getExit() {
    long cPtr = gphoto2JNI.CameraFunctions_exit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_struct__GPContext__int(cPtr, false);
  }

  public void setGet_config(SWIGTYPE_p_f_p_struct__Camera_p_p_struct__CameraWidget_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_get_config_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_p_struct__CameraWidget_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_p_struct__CameraWidget_p_struct__GPContext__int getGet_config() {
    long cPtr = gphoto2JNI.CameraFunctions_get_config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_p_struct__CameraWidget_p_struct__GPContext__int(cPtr, false);
  }

  public void setSet_config(SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraWidget_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_set_config_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraWidget_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraWidget_p_struct__GPContext__int getSet_config() {
    long cPtr = gphoto2JNI.CameraFunctions_set_config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraWidget_p_struct__GPContext__int(cPtr, false);
  }

  public void setCapture(SWIGTYPE_p_f_p_struct__Camera_enum_CameraCaptureType_p_CameraFilePath_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_capture_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_enum_CameraCaptureType_p_CameraFilePath_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_enum_CameraCaptureType_p_CameraFilePath_p_struct__GPContext__int getCapture() {
    long cPtr = gphoto2JNI.CameraFunctions_capture_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_enum_CameraCaptureType_p_CameraFilePath_p_struct__GPContext__int(cPtr, false);
  }

  public void setCapture_preview(SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraFile_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_capture_preview_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraFile_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraFile_p_struct__GPContext__int getCapture_preview() {
    long cPtr = gphoto2JNI.CameraFunctions_capture_preview_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_struct__CameraFile_p_struct__GPContext__int(cPtr, false);
  }

  public void setSummary(SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_summary_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int getSummary() {
    long cPtr = gphoto2JNI.CameraFunctions_summary_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int(cPtr, false);
  }

  public void setManual(SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_manual_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int getManual() {
    long cPtr = gphoto2JNI.CameraFunctions_manual_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int(cPtr, false);
  }

  public void setAbout(SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_about_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int getAbout() {
    long cPtr = gphoto2JNI.CameraFunctions_about_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_p_CameraText_p_struct__GPContext__int(cPtr, false);
  }

  public void setWait_for_event(SWIGTYPE_p_f_p_struct__Camera_int_p_enum_CameraEventType_p_p_void_p_struct__GPContext__int value) {
    gphoto2JNI.CameraFunctions_wait_for_event_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__Camera_int_p_enum_CameraEventType_p_p_void_p_struct__GPContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__Camera_int_p_enum_CameraEventType_p_p_void_p_struct__GPContext__int getWait_for_event() {
    long cPtr = gphoto2JNI.CameraFunctions_wait_for_event_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__Camera_int_p_enum_CameraEventType_p_p_void_p_struct__GPContext__int(cPtr, false);
  }

  public void setReserved1(SWIGTYPE_p_void value) {
    gphoto2JNI.CameraFunctions_reserved1_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved1() {
    long cPtr = gphoto2JNI.CameraFunctions_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_void value) {
    gphoto2JNI.CameraFunctions_reserved2_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved2() {
    long cPtr = gphoto2JNI.CameraFunctions_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReserved3(SWIGTYPE_p_void value) {
    gphoto2JNI.CameraFunctions_reserved3_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved3() {
    long cPtr = gphoto2JNI.CameraFunctions_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReserved4(SWIGTYPE_p_void value) {
    gphoto2JNI.CameraFunctions_reserved4_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved4() {
    long cPtr = gphoto2JNI.CameraFunctions_reserved4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReserved5(SWIGTYPE_p_void value) {
    gphoto2JNI.CameraFunctions_reserved5_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved5() {
    long cPtr = gphoto2JNI.CameraFunctions_reserved5_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReserved6(SWIGTYPE_p_void value) {
    gphoto2JNI.CameraFunctions_reserved6_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved6() {
    long cPtr = gphoto2JNI.CameraFunctions_reserved6_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReserved7(SWIGTYPE_p_void value) {
    gphoto2JNI.CameraFunctions_reserved7_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved7() {
    long cPtr = gphoto2JNI.CameraFunctions_reserved7_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public CameraFunctions() {
    this(gphoto2JNI.new_CameraFunctions(), true);
  }

}
