/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class CameraFileInfoPreview {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CameraFileInfoPreview(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CameraFileInfoPreview obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_CameraFileInfoPreview(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFields(CameraFileInfoFields value) {
    gphoto2JNI.CameraFileInfoPreview_fields_set(swigCPtr, this, value.swigValue());
  }

  public CameraFileInfoFields getFields() {
    return CameraFileInfoFields.swigToEnum(gphoto2JNI.CameraFileInfoPreview_fields_get(swigCPtr, this));
  }

  public void setStatus(CameraFileStatus value) {
    gphoto2JNI.CameraFileInfoPreview_status_set(swigCPtr, this, value.swigValue());
  }

  public CameraFileStatus getStatus() {
    return CameraFileStatus.swigToEnum(gphoto2JNI.CameraFileInfoPreview_status_get(swigCPtr, this));
  }

  public void setSize(long value) {
    gphoto2JNI.CameraFileInfoPreview_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return gphoto2JNI.CameraFileInfoPreview_size_get(swigCPtr, this);
  }

  public void setType(String value) {
    gphoto2JNI.CameraFileInfoPreview_type_set(swigCPtr, this, value);
  }

  public String getType() {
    return gphoto2JNI.CameraFileInfoPreview_type_get(swigCPtr, this);
  }

  public void setWidth(long value) {
    gphoto2JNI.CameraFileInfoPreview_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return gphoto2JNI.CameraFileInfoPreview_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    gphoto2JNI.CameraFileInfoPreview_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return gphoto2JNI.CameraFileInfoPreview_height_get(swigCPtr, this);
  }

  public CameraFileInfoPreview() {
    this(gphoto2JNI.new_CameraFileInfoPreview(), true);
  }

}
