/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraFolderOperation {
  public final static CameraFolderOperation GP_FOLDER_OPERATION_NONE = new CameraFolderOperation("GP_FOLDER_OPERATION_NONE", 0);
  public final static CameraFolderOperation GP_FOLDER_OPERATION_DELETE_ALL = new CameraFolderOperation("GP_FOLDER_OPERATION_DELETE_ALL", 1 << 0);
  public final static CameraFolderOperation GP_FOLDER_OPERATION_PUT_FILE = new CameraFolderOperation("GP_FOLDER_OPERATION_PUT_FILE", 1 << 1);
  public final static CameraFolderOperation GP_FOLDER_OPERATION_MAKE_DIR = new CameraFolderOperation("GP_FOLDER_OPERATION_MAKE_DIR", 1 << 2);
  public final static CameraFolderOperation GP_FOLDER_OPERATION_REMOVE_DIR = new CameraFolderOperation("GP_FOLDER_OPERATION_REMOVE_DIR", 1 << 3);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraFolderOperation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraFolderOperation.class + " with value " + swigValue);
  }

  private CameraFolderOperation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraFolderOperation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraFolderOperation(String swigName, CameraFolderOperation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraFolderOperation[] swigValues = { GP_FOLDER_OPERATION_NONE, GP_FOLDER_OPERATION_DELETE_ALL, GP_FOLDER_OPERATION_PUT_FILE, GP_FOLDER_OPERATION_MAKE_DIR, GP_FOLDER_OPERATION_REMOVE_DIR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

