/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraWidgetType {
  public final static CameraWidgetType GP_WIDGET_WINDOW = new CameraWidgetType("GP_WIDGET_WINDOW");
  public final static CameraWidgetType GP_WIDGET_SECTION = new CameraWidgetType("GP_WIDGET_SECTION");
  public final static CameraWidgetType GP_WIDGET_TEXT = new CameraWidgetType("GP_WIDGET_TEXT");
  public final static CameraWidgetType GP_WIDGET_RANGE = new CameraWidgetType("GP_WIDGET_RANGE");
  public final static CameraWidgetType GP_WIDGET_TOGGLE = new CameraWidgetType("GP_WIDGET_TOGGLE");
  public final static CameraWidgetType GP_WIDGET_RADIO = new CameraWidgetType("GP_WIDGET_RADIO");
  public final static CameraWidgetType GP_WIDGET_MENU = new CameraWidgetType("GP_WIDGET_MENU");
  public final static CameraWidgetType GP_WIDGET_BUTTON = new CameraWidgetType("GP_WIDGET_BUTTON");
  public final static CameraWidgetType GP_WIDGET_DATE = new CameraWidgetType("GP_WIDGET_DATE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraWidgetType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraWidgetType.class + " with value " + swigValue);
  }

  private CameraWidgetType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraWidgetType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraWidgetType(String swigName, CameraWidgetType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraWidgetType[] swigValues = { GP_WIDGET_WINDOW, GP_WIDGET_SECTION, GP_WIDGET_TEXT, GP_WIDGET_RANGE, GP_WIDGET_TOGGLE, GP_WIDGET_RADIO, GP_WIDGET_MENU, GP_WIDGET_BUTTON, GP_WIDGET_DATE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

