/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraStorageType {
  public final static CameraStorageType GP_STORAGEINFO_ST_UNKNOWN = new CameraStorageType("GP_STORAGEINFO_ST_UNKNOWN", 0);
  public final static CameraStorageType GP_STORAGEINFO_ST_FIXED_ROM = new CameraStorageType("GP_STORAGEINFO_ST_FIXED_ROM", 1);
  public final static CameraStorageType GP_STORAGEINFO_ST_REMOVABLE_ROM = new CameraStorageType("GP_STORAGEINFO_ST_REMOVABLE_ROM", 2);
  public final static CameraStorageType GP_STORAGEINFO_ST_FIXED_RAM = new CameraStorageType("GP_STORAGEINFO_ST_FIXED_RAM", 3);
  public final static CameraStorageType GP_STORAGEINFO_ST_REMOVABLE_RAM = new CameraStorageType("GP_STORAGEINFO_ST_REMOVABLE_RAM", 4);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraStorageType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraStorageType.class + " with value " + swigValue);
  }

  private CameraStorageType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraStorageType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraStorageType(String swigName, CameraStorageType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraStorageType[] swigValues = { GP_STORAGEINFO_ST_UNKNOWN, GP_STORAGEINFO_ST_FIXED_ROM, GP_STORAGEINFO_ST_REMOVABLE_ROM, GP_STORAGEINFO_ST_FIXED_RAM, GP_STORAGEINFO_ST_REMOVABLE_RAM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

