/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraFileOperation {
  public final static CameraFileOperation GP_FILE_OPERATION_NONE = new CameraFileOperation("GP_FILE_OPERATION_NONE", 0);
  public final static CameraFileOperation GP_FILE_OPERATION_DELETE = new CameraFileOperation("GP_FILE_OPERATION_DELETE", 1 << 1);
  public final static CameraFileOperation GP_FILE_OPERATION_PREVIEW = new CameraFileOperation("GP_FILE_OPERATION_PREVIEW", 1 << 3);
  public final static CameraFileOperation GP_FILE_OPERATION_RAW = new CameraFileOperation("GP_FILE_OPERATION_RAW", 1 << 4);
  public final static CameraFileOperation GP_FILE_OPERATION_AUDIO = new CameraFileOperation("GP_FILE_OPERATION_AUDIO", 1 << 5);
  public final static CameraFileOperation GP_FILE_OPERATION_EXIF = new CameraFileOperation("GP_FILE_OPERATION_EXIF", 1 << 6);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraFileOperation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraFileOperation.class + " with value " + swigValue);
  }

  private CameraFileOperation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraFileOperation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraFileOperation(String swigName, CameraFileOperation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraFileOperation[] swigValues = { GP_FILE_OPERATION_NONE, GP_FILE_OPERATION_DELETE, GP_FILE_OPERATION_PREVIEW, GP_FILE_OPERATION_RAW, GP_FILE_OPERATION_AUDIO, GP_FILE_OPERATION_EXIF };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

