/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraFileType {
  public final static CameraFileType GP_FILE_TYPE_PREVIEW = new CameraFileType("GP_FILE_TYPE_PREVIEW");
  public final static CameraFileType GP_FILE_TYPE_NORMAL = new CameraFileType("GP_FILE_TYPE_NORMAL");
  public final static CameraFileType GP_FILE_TYPE_RAW = new CameraFileType("GP_FILE_TYPE_RAW");
  public final static CameraFileType GP_FILE_TYPE_AUDIO = new CameraFileType("GP_FILE_TYPE_AUDIO");
  public final static CameraFileType GP_FILE_TYPE_EXIF = new CameraFileType("GP_FILE_TYPE_EXIF");
  public final static CameraFileType GP_FILE_TYPE_METADATA = new CameraFileType("GP_FILE_TYPE_METADATA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraFileType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraFileType.class + " with value " + swigValue);
  }

  private CameraFileType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraFileType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraFileType(String swigName, CameraFileType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraFileType[] swigValues = { GP_FILE_TYPE_PREVIEW, GP_FILE_TYPE_NORMAL, GP_FILE_TYPE_RAW, GP_FILE_TYPE_AUDIO, GP_FILE_TYPE_EXIF, GP_FILE_TYPE_METADATA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

