/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class CameraStorageAccessType {
  public final static CameraStorageAccessType GP_STORAGEINFO_AC_READWRITE = new CameraStorageAccessType("GP_STORAGEINFO_AC_READWRITE", 0);
  public final static CameraStorageAccessType GP_STORAGEINFO_AC_READONLY = new CameraStorageAccessType("GP_STORAGEINFO_AC_READONLY", 1);
  public final static CameraStorageAccessType GP_STORAGEINFO_AC_READONLY_WITH_DELETE = new CameraStorageAccessType("GP_STORAGEINFO_AC_READONLY_WITH_DELETE", 2);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraStorageAccessType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraStorageAccessType.class + " with value " + swigValue);
  }

  private CameraStorageAccessType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraStorageAccessType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraStorageAccessType(String swigName, CameraStorageAccessType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraStorageAccessType[] swigValues = { GP_STORAGEINFO_AC_READWRITE, GP_STORAGEINFO_AC_READONLY, GP_STORAGEINFO_AC_READONLY_WITH_DELETE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

