/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class CameraFileInfoFile {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CameraFileInfoFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CameraFileInfoFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_CameraFileInfoFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFields(CameraFileInfoFields value) {
    gphoto2JNI.CameraFileInfoFile_fields_set(swigCPtr, this, value.swigValue());
  }

  public CameraFileInfoFields getFields() {
    return CameraFileInfoFields.swigToEnum(gphoto2JNI.CameraFileInfoFile_fields_get(swigCPtr, this));
  }

  public void setStatus(CameraFileStatus value) {
    gphoto2JNI.CameraFileInfoFile_status_set(swigCPtr, this, value.swigValue());
  }

  public CameraFileStatus getStatus() {
    return CameraFileStatus.swigToEnum(gphoto2JNI.CameraFileInfoFile_status_get(swigCPtr, this));
  }

  public void setSize(long value) {
    gphoto2JNI.CameraFileInfoFile_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return gphoto2JNI.CameraFileInfoFile_size_get(swigCPtr, this);
  }

  public void setType(String value) {
    gphoto2JNI.CameraFileInfoFile_type_set(swigCPtr, this, value);
  }

  public String getType() {
    return gphoto2JNI.CameraFileInfoFile_type_get(swigCPtr, this);
  }

  public void setWidth(long value) {
    gphoto2JNI.CameraFileInfoFile_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return gphoto2JNI.CameraFileInfoFile_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    gphoto2JNI.CameraFileInfoFile_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return gphoto2JNI.CameraFileInfoFile_height_get(swigCPtr, this);
  }

  public void setName(String value) {
    gphoto2JNI.CameraFileInfoFile_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return gphoto2JNI.CameraFileInfoFile_name_get(swigCPtr, this);
  }

  public void setPermissions(CameraFilePermissions value) {
    gphoto2JNI.CameraFileInfoFile_permissions_set(swigCPtr, this, value.swigValue());
  }

  public CameraFilePermissions getPermissions() {
    return CameraFilePermissions.swigToEnum(gphoto2JNI.CameraFileInfoFile_permissions_get(swigCPtr, this));
  }

  public void setMtime(SWIGTYPE_p_time_t value) {
    gphoto2JNI.CameraFileInfoFile_mtime_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getMtime() {
    return new SWIGTYPE_p_time_t(gphoto2JNI.CameraFileInfoFile_mtime_get(swigCPtr, this), true);
  }

  public CameraFileInfoFile() {
    this(gphoto2JNI.new_CameraFileInfoFile(), true);
  }

}
