/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class GPContextFeedback {
  public final static GPContextFeedback GP_CONTEXT_FEEDBACK_OK = new GPContextFeedback("GP_CONTEXT_FEEDBACK_OK");
  public final static GPContextFeedback GP_CONTEXT_FEEDBACK_CANCEL = new GPContextFeedback("GP_CONTEXT_FEEDBACK_CANCEL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GPContextFeedback swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GPContextFeedback.class + " with value " + swigValue);
  }

  private GPContextFeedback(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GPContextFeedback(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GPContextFeedback(String swigName, GPContextFeedback swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GPContextFeedback[] swigValues = { GP_CONTEXT_FEEDBACK_OK, GP_CONTEXT_FEEDBACK_CANCEL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

