/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public interface gphoto2Constants {
  public final static String GP_MIME_WAV = "audio/wav";
  public final static String GP_MIME_RAW = "image/x-raw";
  public final static String GP_MIME_PNG = "image/png";
  public final static String GP_MIME_PGM = "image/x-portable-graymap";
  public final static String GP_MIME_PPM = "image/x-portable-pixmap";
  public final static String GP_MIME_PNM = "image/x-portable-anymap";
  public final static String GP_MIME_JPEG = "image/jpeg";
  public final static String GP_MIME_TIFF = "image/tiff";
  public final static String GP_MIME_BMP = "image/bmp";
  public final static String GP_MIME_QUICKTIME = "video/quicktime";
  public final static String GP_MIME_AVI = "video/x-msvideo";
  public final static String GP_MIME_CRW = "image/x-canon-raw";
  public final static String GP_MIME_CR2 = "image/x-canon-cr2";
  public final static String GP_MIME_UNKNOWN = "application/octet-stream";
  public final static String GP_MIME_EXIF = "application/x-exif";
  public final static String GP_MIME_MP3 = "audio/mpeg";
  public final static String GP_MIME_OGG = "application/ogg";
  public final static String GP_MIME_WMA = "audio/x-wma";
  public final static String GP_MIME_ASF = "audio/x-asf";
  public final static String GP_MIME_MPEG = "video/mpeg";
  public final static int TRUE = 1;
  public final static int FALSE = 0;
  public final static int GP_PORT_MAX_BUF_LEN = 4096;
  public final static int GP_PORT_USB_ENDPOINT_IN = 0;
  public final static int GP_PORT_USB_ENDPOINT_OUT = GP_PORT_USB_ENDPOINT_IN + 1;
  public final static int GP_PORT_USB_ENDPOINT_INT = GP_PORT_USB_ENDPOINT_OUT + 1;

  public final static int GP_OK = 0;
  public final static int GP_ERROR = -1;
  public final static int GP_ERROR_BAD_PARAMETERS = -2;
  public final static int GP_ERROR_NO_MEMORY = -3;
  public final static int GP_ERROR_LIBRARY = -4;
  public final static int GP_ERROR_UNKNOWN_PORT = -5;
  public final static int GP_ERROR_NOT_SUPPORTED = -6;
  public final static int GP_ERROR_IO = -7;
  public final static int GP_ERROR_FIXED_LIMIT_EXCEEDED = -8;
  public final static int GP_ERROR_TIMEOUT = -10;
  public final static int GP_ERROR_IO_SUPPORTED_SERIAL = -20;
  public final static int GP_ERROR_IO_SUPPORTED_USB = -21;
  public final static int GP_ERROR_IO_INIT = -31;
  public final static int GP_ERROR_IO_READ = -34;
  public final static int GP_ERROR_IO_WRITE = -35;
  public final static int GP_ERROR_IO_UPDATE = -37;
  public final static int GP_ERROR_IO_SERIAL_SPEED = -41;
  public final static int GP_ERROR_IO_USB_CLEAR_HALT = -51;
  public final static int GP_ERROR_IO_USB_FIND = -52;
  public final static int GP_ERROR_IO_USB_CLAIM = -53;
  public final static int GP_ERROR_IO_LOCK = -60;
  public final static int GP_ERROR_HAL = -70;
  public final static int GP_ERROR_CORRUPTED_DATA = -102;
  public final static int GP_ERROR_FILE_EXISTS = -103;
  public final static int GP_ERROR_MODEL_NOT_FOUND = -105;
  public final static int GP_ERROR_DIRECTORY_NOT_FOUND = -107;
  public final static int GP_ERROR_FILE_NOT_FOUND = -108;
  public final static int GP_ERROR_DIRECTORY_EXISTS = -109;
  public final static int GP_ERROR_CAMERA_BUSY = -110;
  public final static int GP_ERROR_PATH_NOT_ABSOLUTE = -111;
  public final static int GP_ERROR_CANCEL = -112;
  public final static int GP_ERROR_CAMERA_ERROR = -113;
  public final static int GP_ERROR_OS_FAILURE = -114;
  public final static int GP_ERROR_NO_SPACE = -115;
}
