/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class GPLevel {
  public final static GPLevel GP_LEVEL_LOW = new GPLevel("GP_LEVEL_LOW", 0);
  public final static GPLevel GP_LEVEL_HIGH = new GPLevel("GP_LEVEL_HIGH", 1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GPLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GPLevel.class + " with value " + swigValue);
  }

  private GPLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GPLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GPLevel(String swigName, GPLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GPLevel[] swigValues = { GP_LEVEL_LOW, GP_LEVEL_HIGH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

