/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class GPPortInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GPPortInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GPPortInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_GPPortInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(GPPortType value) {
    gphoto2JNI.GPPortInfo_type_set(swigCPtr, this, value.swigValue());
  }

  public GPPortType getType() {
    return GPPortType.swigToEnum(gphoto2JNI.GPPortInfo_type_get(swigCPtr, this));
  }

  public void setName(String value) {
    gphoto2JNI.GPPortInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return gphoto2JNI.GPPortInfo_name_get(swigCPtr, this);
  }

  public void setPath(String value) {
    gphoto2JNI.GPPortInfo_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return gphoto2JNI.GPPortInfo_path_get(swigCPtr, this);
  }

  public void setLibrary_filename(String value) {
    gphoto2JNI.GPPortInfo_library_filename_set(swigCPtr, this, value);
  }

  public String getLibrary_filename() {
    return gphoto2JNI.GPPortInfo_library_filename_get(swigCPtr, this);
  }

  public GPPortInfo() {
    this(gphoto2JNI.new_GPPortInfo(), true);
  }

}
