/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class GPPortSerialParity {
  public final static GPPortSerialParity GP_PORT_SERIAL_PARITY_OFF = new GPPortSerialParity("GP_PORT_SERIAL_PARITY_OFF", 0);
  public final static GPPortSerialParity GP_PORT_SERIAL_PARITY_EVEN = new GPPortSerialParity("GP_PORT_SERIAL_PARITY_EVEN");
  public final static GPPortSerialParity GP_PORT_SERIAL_PARITY_ODD = new GPPortSerialParity("GP_PORT_SERIAL_PARITY_ODD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GPPortSerialParity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GPPortSerialParity.class + " with value " + swigValue);
  }

  private GPPortSerialParity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GPPortSerialParity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GPPortSerialParity(String swigName, GPPortSerialParity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GPPortSerialParity[] swigValues = { GP_PORT_SERIAL_PARITY_OFF, GP_PORT_SERIAL_PARITY_EVEN, GP_PORT_SERIAL_PARITY_ODD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

