/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class GPPortType {
  public final static GPPortType GP_PORT_NONE = new GPPortType("GP_PORT_NONE", 0);
  public final static GPPortType GP_PORT_SERIAL = new GPPortType("GP_PORT_SERIAL", 1 << 0);
  public final static GPPortType GP_PORT_USB = new GPPortType("GP_PORT_USB", 1 << 2);
  public final static GPPortType GP_PORT_DISK = new GPPortType("GP_PORT_DISK", 1 << 3);
  public final static GPPortType GP_PORT_PTPIP = new GPPortType("GP_PORT_PTPIP", 1 << 4);
  public final static GPPortType GP_PORT_USB_DISK_DIRECT = new GPPortType("GP_PORT_USB_DISK_DIRECT", 1 << 5);
  public final static GPPortType GP_PORT_USB_SCSI = new GPPortType("GP_PORT_USB_SCSI", 1 << 6);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GPPortType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GPPortType.class + " with value " + swigValue);
  }

  private GPPortType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GPPortType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GPPortType(String swigName, GPPortType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GPPortType[] swigValues = { GP_PORT_NONE, GP_PORT_SERIAL, GP_PORT_USB, GP_PORT_DISK, GP_PORT_PTPIP, GP_PORT_USB_DISK_DIRECT, GP_PORT_USB_SCSI };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

