/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class GPPortSettingsUSB {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GPPortSettingsUSB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GPPortSettingsUSB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_GPPortSettingsUSB(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInep(int value) {
    gphoto2JNI.GPPortSettingsUSB_inep_set(swigCPtr, this, value);
  }

  public int getInep() {
    return gphoto2JNI.GPPortSettingsUSB_inep_get(swigCPtr, this);
  }

  public void setOutep(int value) {
    gphoto2JNI.GPPortSettingsUSB_outep_set(swigCPtr, this, value);
  }

  public int getOutep() {
    return gphoto2JNI.GPPortSettingsUSB_outep_get(swigCPtr, this);
  }

  public void setIntep(int value) {
    gphoto2JNI.GPPortSettingsUSB_intep_set(swigCPtr, this, value);
  }

  public int getIntep() {
    return gphoto2JNI.GPPortSettingsUSB_intep_get(swigCPtr, this);
  }

  public void setConfig(int value) {
    gphoto2JNI.GPPortSettingsUSB_config_set(swigCPtr, this, value);
  }

  public int getConfig() {
    return gphoto2JNI.GPPortSettingsUSB_config_get(swigCPtr, this);
  }

  public void set_interface(int value) {
    gphoto2JNI.GPPortSettingsUSB__interface_set(swigCPtr, this, value);
  }

  public int get_interface() {
    return gphoto2JNI.GPPortSettingsUSB__interface_get(swigCPtr, this);
  }

  public void setAltsetting(int value) {
    gphoto2JNI.GPPortSettingsUSB_altsetting_set(swigCPtr, this, value);
  }

  public int getAltsetting() {
    return gphoto2JNI.GPPortSettingsUSB_altsetting_get(swigCPtr, this);
  }

  public void setMaxpacketsize(int value) {
    gphoto2JNI.GPPortSettingsUSB_maxpacketsize_set(swigCPtr, this, value);
  }

  public int getMaxpacketsize() {
    return gphoto2JNI.GPPortSettingsUSB_maxpacketsize_get(swigCPtr, this);
  }

  public void setPort(String value) {
    gphoto2JNI.GPPortSettingsUSB_port_set(swigCPtr, this, value);
  }

  public String getPort() {
    return gphoto2JNI.GPPortSettingsUSB_port_get(swigCPtr, this);
  }

  public GPPortSettingsUSB() {
    this(gphoto2JNI.new_GPPortSettingsUSB(), true);
  }

}
