/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class GPPortSettingsSerial {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GPPortSettingsSerial(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GPPortSettingsSerial obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gphoto2JNI.delete_GPPortSettingsSerial(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPort(String value) {
    gphoto2JNI.GPPortSettingsSerial_port_set(swigCPtr, this, value);
  }

  public String getPort() {
    return gphoto2JNI.GPPortSettingsSerial_port_get(swigCPtr, this);
  }

  public void setSpeed(int value) {
    gphoto2JNI.GPPortSettingsSerial_speed_set(swigCPtr, this, value);
  }

  public int getSpeed() {
    return gphoto2JNI.GPPortSettingsSerial_speed_get(swigCPtr, this);
  }

  public void setBits(int value) {
    gphoto2JNI.GPPortSettingsSerial_bits_set(swigCPtr, this, value);
  }

  public int getBits() {
    return gphoto2JNI.GPPortSettingsSerial_bits_get(swigCPtr, this);
  }

  public void setParity(GPPortSerialParity value) {
    gphoto2JNI.GPPortSettingsSerial_parity_set(swigCPtr, this, value.swigValue());
  }

  public GPPortSerialParity getParity() {
    return GPPortSerialParity.swigToEnum(gphoto2JNI.GPPortSettingsSerial_parity_get(swigCPtr, this));
  }

  public void setStopbits(int value) {
    gphoto2JNI.GPPortSettingsSerial_stopbits_set(swigCPtr, this, value);
  }

  public int getStopbits() {
    return gphoto2JNI.GPPortSettingsSerial_stopbits_get(swigCPtr, this);
  }

  public GPPortSettingsSerial() {
    this(gphoto2JNI.new_GPPortSettingsSerial(), true);
  }

}
