/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public final class GPVersionVerbosity {
  public final static GPVersionVerbosity GP_VERSION_SHORT = new GPVersionVerbosity("GP_VERSION_SHORT", 0);
  public final static GPVersionVerbosity GP_VERSION_VERBOSE = new GPVersionVerbosity("GP_VERSION_VERBOSE", 1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GPVersionVerbosity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GPVersionVerbosity.class + " with value " + swigValue);
  }

  private GPVersionVerbosity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GPVersionVerbosity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GPVersionVerbosity(String swigName, GPVersionVerbosity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GPVersionVerbosity[] swigValues = { GP_VERSION_SHORT, GP_VERSION_VERBOSE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

