/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig.org.gphoto2;

public class SWIGTYPE_p__CameraWidget {
  private long swigCPtr;

  protected SWIGTYPE_p__CameraWidget(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p__CameraWidget() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p__CameraWidget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

